--crearemos una tabla muy simple para probar el poder de SQL

--CREATE TABLE DANCE(ID_DANCE INTEGER, NOMBRE VARCHAR2(40), EDAD INTEGER);
--VENDEMOS EL SERVIDOR EN MODO DE DESARROLLADOR 
SET SERVEROUTPUT ON;
--VAMOS A EMPEZAR CON UN BLOQUE EL SQL

DECLARE
--AQUI SE DECLARAN LAS VARIABLES A USARSE
EDAD INTEGER;
YEARS INTEGER;
BEGIN


YEARS:=21;
EDAD:=YEARS*365;

DBMS_OUTPUT.PUT_LINE('TU EDAD EN DIAS ES'||EDAD);

END;
/
