--crearemos una tabla muy simple para probar el poder de SQL
CREATE TABLE DANCE
  (
    ID_DANCE INTEGER,
    NOMBRE   VARCHAR2(40),
    EDAD     INTEGER
  );
--VENDEMOS EL SERVIDOR EN MODO DE DESARROLLADOR
SET SERVEROUTPUT ON;
--VAMOS A EMPEZAR CON UN BLOQUE EL SQL
DECLARE
  --AQUI SE DECLARAN LAS VARIABLES A USARSE
  EDAD  INTEGER;
  YEARS INTEGER;
BEGIN
  YEARS:=21;
  EDAD :=YEARS*365;
  DBMS_OUTPUT.PUT_LINE('TU EDAD EN DIAS ES'||EDAD);
END;
/
--crear un bloque pl en sql que genere 200 000 registros en secuencia ascendente en la tabla dance
BEGIN
  FOR I IN 1..200000
  LOOP
    INSERT INTO DANCE VALUES
      (I,'CAMPOS',44
      );
  END LOOP;
END;
/
SELECT *FROM DANCE;
--SISTEMA DE PELICULAS
CREATE TABLE PELICULA
  (
    ID_PELICULA INTEGER,
    TITULO      VARCHAR2 (120),
    SINOPSIS    VARCHAR2 (500),
    CLASICACION VARCHAR2 (5),
    CONSTRAINT PK_ID_PELICULA PRIMARY KEY(ID_PELICULA)); 
    DESCRIBE PELICULA;
    
    CREATE TABLE HORARIO (ID_HORARIO INTEGER,
    ID_PELICULA INTEGER,
    HORARIO VARCHAR2(5),
    CONSTRAINT PK_ID_HORARIO PRIMARY KEY(ID_HORARIO),
    CONSTRAINT FK1_ID_PELICULA FOREIGN KEY(ID_PELICULA) REFERENCES PELICULA(ID_PELICULA));
